# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('url', models.CharField(max_length=150, verbose_name='Url')),
                ('content', models.TextField(verbose_name='Post')),
            ],
        ),
    ]
