# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import facerecognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='file',
            field=models.FileField(upload_to=facerecognition.models.sesion_path),
        ),
    ]
