# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_auto_20170815_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='url',
        ),
    ]
